### ISSUE TITLE
Double quotes not properly handled

### ISSUE THREAD

**Issue by J535D165** [erikvullings/xref2csv#1]
As reported in https://github.com/asreview/asreview/issues/919, `pandas` fails to read `xref2csv` output when guessing delimiter and double quotes are present. 

A potential solution might be to enclose the field with double quotes. 

See https://datatracker.ietf.org/doc/html/rfc4180
```
Each field may or may not be enclosed in double quotes (however
       some programs, such as Microsoft Excel, do not use double quotes
       at all).  If fields are not enclosed with double quotes, then
       double quotes may not appear inside the fields.
```

**Comment by erikvullings** [comment]
Unfortunately, enclosing a field with double quotes (so "=> """") does not work, and ASreview still cannot read the CSV. I've also tried to escape it using a " => \" and " => "". Although these solutions work, they also show up in the ASreview interface, so that is not very elegant either. 
I've finally chosen to replace " => ' and that is accepted and does not look to ugly either.
